version: '3'
services:
  mongodb:
    container_name: 'mongodb'
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - network1  
    volumes:
      - "mongodata:/data/db"    
  dictionary:
    container_name: 'dictionary'
    image: dictionaryapi
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - network1
    depends_on:
      - mongodb
    environment:
      - SERVER=mongodb:27017  
      - DATABASENAME=dictionary

volumes:
  mongodata:
networks:
  network1:
    driver: bridge
