version: '3'
services:
  mongo:
    container_name: 'mongo'
    image: mongo
    # ports:
    #   - "27017:27017"
    networks:
      - network1  
    volumes:
      - "mongodata:/data/db"    
  kafka:
    container_name: 'kafka'
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - network1
  dictionary:
    container_name: 'dictionary'
    image: dictionaryapi
    ports:
      - "8080:8080"
    networks:
      - network1
    depends_on:
      - mongo
      - kafka
    environment:
      - SERVER=mongo:27017  
      - DATABASENAME=dictionary

volumes:
  mongodata:
networks:
  network1:
    driver: bridge
