version: '3'
services:
  mongodb:
    container_name: 'mongodb'
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - network1  
    volumes:
      - "mongodata:/data/db"    
  dictionary:
    container_name: 'dictionary'
    image: dictionaryapi
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - network1
    depends_on:
      - mongodb
    environment:
      - SERVER=mongodb:27017  
      - DATABASENAME=dictionary

volumes:
  mongodata:
networks:
  network1:
    driver: bridge

# When docker-compose is run in Windows 10 with Hyper-V
# go to "localhost:8080/definition" to see the output.
# When docker-compose is run using Docker Toolbox
# go to "192.168.99.100:8080/definition" to see the output.
# "192.168.99.100" is the ip address of your docker-machine.
# Execute `$ docker-machine ip` to get ip address of your docker-machine.
